import { mkdir, mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { analyze, deleteLocalData, optimizeResume, renderResume } from "../../src/commands.js";
import { stateDirectory } from "../../src/io/private-store.js";
import { FakeCore } from "../helpers/fake-core.js";
const temp = () => mkdtemp(join(tmpdir(), "jfs-actions-")); const jd = "Backend engineer must build reliable Node.js APIs and use Redis caching in production.";
describe("actions", () => {
  it("writes a deidentified sourced analysis", async () => { const root = await temp(); await writeFile(join(root, "cv.txt"), "Node course project"); const core = new FakeCore(); const result = await analyze(core, root, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json", "markdown"] }); expect(result.learningPaths).toEqual(expect.arrayContaining([expect.objectContaining({ gapRequirementId: "req-redis" })])); expect(await readFile(join(root, ".job-fit/reports/latest-analysis.md"), "utf8")).toContain("PLATFORM_GENERATED"); });
  it("optimizes only a fact-verified resume", async () => { const root = await temp(); await writeFile(join(root, "cv.txt"), "Node course project"); await analyze(new FakeCore(), root, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json"] }); const result = await optimizeResume(new FakeCore(), root, { analysisFile: ".job-fit/reports/latest-analysis.json", selectedJobId: "backend", confirmedFacts: [], confirmedChangeIds: [], templateId: "ats-classic" }) as { factualVerification: { passed: boolean }; resumeModelFile: string }; expect(result.factualVerification.passed).toBe(true); expect(await readFile(join(root, result.resumeModelFile), "utf8")).toContain("course_project"); });
  it("returns a sanitized proposal without saving an unconfirmed resume model", async () => {
    const root = await temp(); await writeFile(join(root, "cv.txt"), "Node course project"); await analyze(new FakeCore(), root, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json"] }); const core = new FakeCore(); let confirmedDraft: unknown;
    core.optimizeResume = (async (input: Parameters<FakeCore["optimizeResume"]>[0]) => { const proposal = { id: "draft", jobId: "backend", template: "CLASSIC" as const, sections: [{ heading: "Contact", bullets: [{ id: "risk", text: "Chen Pengwen | chen@example.com", highRisk: true, confirmed: false, evidenceIds: [] }] }] }; if (input.proposalDraft) { confirmedDraft = input.proposalDraft; const resumeModel = { ...input.proposalDraft, sections: input.proposalDraft.sections.map((section) => ({ ...section, bullets: section.bullets.map((bullet) => ({ ...bullet, confirmed: true })) })) }; return { status: "CONFIRMED" as const, resumeModel, evidence: [], changes: [], riskyChanges: [], requiredConfirmationIds: [], factualVerification: { passed: true, issues: [] } }; } return { status: "NEEDS_CONFIRMATION" as const, resumeModel: proposal, evidence: [], changes: [{ id: "risk", text: "Chen Pengwen | chen@example.com", highRisk: true, confirmed: false, evidenceIds: [] }], riskyChanges: [{ id: "risk", text: "Chen Pengwen | chen@example.com", highRisk: true, confirmed: false, evidenceIds: [] }], requiredConfirmationIds: ["risk"], factualVerification: { passed: false, issues: [{ code: "UNCONFIRMED_HIGH_RISK" as const, path: "sections.0", message: "Chen Pengwen must confirm" }] } }; }) as never;
    const result = await optimizeResume(core, root, { analysisFile: ".job-fit/reports/latest-analysis.json", selectedJobId: "backend", confirmedFacts: [], confirmedChangeIds: [], templateId: "ats-classic" }); const publicText = JSON.stringify(result); const proposalFile = (result as { proposalFile: string }).proposalFile;
    expect(result).toMatchObject({ status: "NEEDS_CONFIRMATION", proposal: { requiredConfirmationIds: ["risk"] } }); expect(proposalFile).toMatch(/^\.job-fit\/proposals\/[0-9a-f-]+\.json$/u); expect(publicText).not.toContain("Chen Pengwen"); expect(publicText).not.toContain("chen@example.com"); expect(await readFile(join(root, proposalFile), "utf8")).toContain("Chen Pengwen"); await expect(readFile(join(root, ".job-fit/resume-models/backend.resume.json"))).rejects.toThrow();
    const confirmed = await optimizeResume(core, root, { analysisFile: ".job-fit/reports/latest-analysis.json", proposalFile, selectedJobId: "backend", confirmedFacts: [], confirmedChangeIds: ["risk"], rejectedChangeIds: [], templateId: "ats-classic" }) as { status: string; resumeModelFile: string }; expect(confirmed.status).toBe("CONFIRMED"); expect(JSON.stringify(confirmedDraft)).toContain("Chen Pengwen"); expect(await readFile(join(root, confirmed.resumeModelFile), "utf8")).toContain("Chen Pengwen");
    const tampered = JSON.parse(await readFile(join(root, proposalFile), "utf8")); tampered.resumeModel.sections[0].bullets[0].text = "tampered after confirmation"; await writeFile(join(root, proposalFile), JSON.stringify(tampered)); await expect(optimizeResume(core, root, { analysisFile: ".job-fit/reports/latest-analysis.json", proposalFile, selectedJobId: "backend", confirmedFacts: [], confirmedChangeIds: ["risk"], rejectedChangeIds: [], templateId: "ats-classic" })).rejects.toThrow(/invalid|match/);
  });
  it("renders verified requested formats only from app-owned private state", async () => { const root = await temp(); await stateDirectory(root); await mkdir(join(root, ".job-fit/resume-models")); await writeFile(join(root, ".job-fit/resume-models/backend.resume.json"), "{}"); const result = await renderResume(new FakeCore(), root, { resumeModelFile: ".job-fit/resume-models/backend.resume.json", outputDirectory: "deliverables", formats: ["docx", "pdf"] }); expect(result.files).toEqual(["deliverables/resume.docx", "deliverables/resume.pdf"]); await writeFile(join(root, "model.json"), "{}"); await expect(renderResume(new FakeCore(), root, { resumeModelFile: "model.json", outputDirectory: "other", formats: ["pdf"] })).rejects.toThrow(/private|app-owned/); });
  it("deletes only marked owned state", async () => { const root = await temp(); await stateDirectory(root); await writeFile(join(root, ".job-fit/private"), "x"); expect(await deleteLocalData(root, { confirm: true })).toEqual({ deleted: true, path: ".job-fit" }); await expect(readFile(join(root, ".job-fit/private"))).rejects.toThrow(); const other = await temp(); await mkdir(join(other, ".job-fit")); await expect(deleteLocalData(other, { confirm: true })).rejects.toThrow("unowned"); });
  it("rejects symlinked private report and resume-model directories", async () => {
    const root = await temp(); const outside = await temp(); await writeFile(join(root, "cv.txt"), "Node course project"); await stateDirectory(root);
    await symlink(outside, join(root, ".job-fit/reports"));
    await expect(analyze(new FakeCore(), root, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json"] })).rejects.toThrow(/unsafe|symbolic/);
    await mkdir(join(root, ".job-fit/reports"), { recursive: true }).catch(() => undefined);
    const root2 = await temp(); const outside2 = await temp(); await writeFile(join(root2, "cv.txt"), "Node course project"); await analyze(new FakeCore(), root2, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json"] }); await symlink(outside2, join(root2, ".job-fit/resume-models"));
    await expect(optimizeResume(new FakeCore(), root2, { analysisFile: ".job-fit/reports/latest-analysis.json", selectedJobId: "backend", confirmedFacts: [], confirmedChangeIds: [], templateId: "ats-classic" })).rejects.toThrow(/unsafe|symbolic/);
  });
  it("never exposes sensitive evidence summaries in public analysis", async () => {
    const root = await temp(); await writeFile(join(root, "cv.txt"), "Chen Pengwen\n北京市朝阳区建国路88号\n身份证 110105199001011234\nNode.js project"); const core = new FakeCore(); const original = core.analyze.bind(core); core.analyze = async (input) => { const result = await original(input); return { ...result, evidence: [{ ...result.evidence[0]!, summary: "Chen Pengwen 北京市朝阳区建国路88号 身份证 110105199001011234" }] }; };
    const result = await analyze(core, root, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json", "markdown"] }); const publicText = `${JSON.stringify(result)}\n${await readFile(join(root, ".job-fit/reports/latest-analysis.json"), "utf8")}\n${await readFile(join(root, ".job-fit/reports/latest-analysis.md"), "utf8")}`;
    for (const secret of ["Chen Pengwen", "北京市朝阳区建国路88号", "110105199001011234"]) expect(publicText).not.toContain(secret);
    const contextPath = String((result as { contextFile: string }).contextFile); expect(await readFile(join(root, contextPath), "utf8")).toContain("Chen Pengwen");
  });
  it("rejects a public report that redirects to a non-context file", async () => {
    const root = await temp(); await writeFile(join(root, "cv.txt"), "Node course project"); const result = await analyze(new FakeCore(), root, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json"] }) as { contextFile: string }; const reportPath = join(root, ".job-fit/reports/latest-analysis.json"); const report = JSON.parse(await readFile(reportPath, "utf8")); await writeFile(join(root, "redirected.json"), await readFile(join(root, result.contextFile))); report.contextFile = "redirected.json"; await writeFile(reportPath, JSON.stringify(report));
    await expect(optimizeResume(new FakeCore(), root, { analysisFile: ".job-fit/reports/latest-analysis.json", selectedJobId: "backend", confirmedFacts: [], confirmedChangeIds: [], templateId: "ats-classic" })).rejects.toThrow(/private context|reference/);
  });
  it("strictly validates the private candidate-name denylist", async () => {
    const root = await temp(); await writeFile(join(root, "cv.txt"), "Alice Smith\nNode course project"); const result = await analyze(new FakeCore(), root, { resumeFiles: ["cv.txt"], jobs: [{ id: "backend", text: jd }], reportFormats: ["json"] }) as { contextFile: string }; const contextPath = join(root, result.contextFile); const context = JSON.parse(await readFile(contextPath, "utf8")); context.candidateNames = ["Alice Smith\nInjected"]; await writeFile(contextPath, JSON.stringify(context)); await expect(optimizeResume(new FakeCore(), root, { analysisFile: ".job-fit/reports/latest-analysis.json", selectedJobId: "backend", confirmedFacts: [], confirmedChangeIds: [], templateId: "ats-classic" })).rejects.toThrow("private analysis context is invalid");
  });
});
